### ISSUE TITLE
Not displaying HTML text?

### ISSUE THREAD

**Issue by Nateliason** [scenevr/htmltexture-component#5]
I have this installed with: 

`<script src="https://rawgit.com/scenevr/htmltexture-component/master/dist/aframe-htmltexture-component.js"></script>`

And then copied your "Goodbye" code from the examples:

`<a-assets><div id="goodbye"><center>1</center></div></a-assets><a-entity geometry="primitive: box" position="3 1 -4" draw="width: 64; height: 64;"htmltexture="asset: #goodbye"></a-entity>`

But the text isn't appearing, any idea what's going on?

**Comment by revolunet** [comment]
what version do you have ? i had it workin with aframe 0.3.2

**Comment by Nateliason** [comment]
@revolunet I got it working, I forgot to include Draw :)
